"""机器控制：GRBL 协议、G-code 生成、串口流式发送、写字起点。"""

from .config import (
    PEN_M3M5,
    PEN_M7M9,
    PEN_CUSTOM,
    PEN_MODES,
    PEN_Z,
    GCodeConfig,
)
from .gcode_gen import (
    GCodeResult,
    collect_strokes,
    format_duration,
    generate_from_document,
    generate_gcode,
)
from .grbl import (
    ALARM_CODES,
    ERROR_CODES,
    MachineStatus,
    ResponseKind,
    alarm_message,
    classify,
    error_message,
    jog_command,
    parse_settings,
    parse_status,
)
from .path_optimizer import draw_length, optimize_order, total_travel
from .profile import (
    MachineProfile,
    motion_time,
    peak_speed,
    suggested_feed,
)
from .serial_link import FakeSerial, GrblLink, LinkEvent, State, list_ports
from .start_point import (
    MODE_CANVAS,
    MODE_CURRENT,
    MODE_LABELS,
    MODE_ORIGIN,
    MODE_REGISTERED,
    StartPoint,
    compute_offset,
    registered_offset,
)

__all__ = [
    "GCodeConfig",
    "PEN_Z",
    "PEN_M3M5",
    "PEN_M7M9",
    "PEN_CUSTOM",
    "PEN_MODES",
    "GCodeResult",
    "generate_gcode",
    "generate_from_document",
    "collect_strokes",
    "format_duration",
    "optimize_order",
    "total_travel",
    "draw_length",
    "MachineStatus",
    "parse_status",
    "classify",
    "ResponseKind",
    "error_message",
    "alarm_message",
    "jog_command",
    "parse_settings",
    "ERROR_CODES",
    "ALARM_CODES",
    "GrblLink",
    "LinkEvent",
    "State",
    "FakeSerial",
    "list_ports",
    "StartPoint",
    "compute_offset",
    "registered_offset",
    "MODE_CANVAS",
    "MODE_ORIGIN",
    "MODE_CURRENT",
    "MODE_REGISTERED",
    "MODE_LABELS",
    "MachineProfile",
    "motion_time",
    "peak_speed",
    "suggested_feed",
]
